version: "3.9"
services: 
  api:
    container_name: api
    image: api
    build:
      context: api/
    ports: 
      - "6001:6001"
    environment: 
      - ASPNETCORE_URLS=http://+:6001
      - Settings:BaseExternalUrl=http://externalapi
      - Settings:Port=7001      
    networks: 
      - resiliency_network
    depends_on: 
      - "externalapi"
  
  externalapi:
    container_name: externalapi
    image: externalapi
    build:
      context: externalapi
    ports: 
      - "7001:7001"    
    environment: 
      - ASPNETCORE_URLS=http://+:7001
    networks: 
      - resiliency_network

networks: 
  resiliency_network:
    driver: bridge